#ifndef MYOS__ATA__IDENTIFYHEADER_H
#define MYOS__ATA__IDENTIFYHEADER_H

#include <common/types.h>

namespace myos
{
    namespace filesystem
    {
        typedef struct _IDENTIFY_DEVICE_DATA {
        struct {
            common::uint16_t Reserved1 : 1;
            common::uint16_t Retired3 : 1;
            common::uint16_t ResponseIncomplete : 1;
            common::uint16_t Retired2 : 3;
            common::uint16_t FixedDevice : 1;
            common::uint16_t RemovableMedia : 1;
            common::uint16_t Retired1 : 7;
            common::uint16_t DeviceType : 1;
        } GeneralConfiguration;
        common::uint16_t NumCylinders;
        common::uint16_t SpecificConfiguration;
        common::uint16_t NumHeads;
        common::uint16_t Retired1[2];
        common::uint16_t NumSectorsPerTrack;
        common::uint16_t VendorUnique1[3];
        common::uint8_t  SerialNumber[20];
        common::uint16_t Retired2[2];
        common::uint16_t Obsolete1;
        common::uint8_t  FirmwareRevision[8];
        common::uint8_t  ModelNumber[40];
        common::uint8_t  MaximumBlockTransfer;
        common::uint8_t  VendorUnique2;
        struct {
            common::uint16_t FeatureSupported : 1;
            common::uint16_t Reserved : 15;
        } TrustedComputing;
        struct {
            common::uint8_t  CurrentLongPhysicalSectorAlignment : 2;
            common::uint8_t  ReservedByte49 : 6;
            common::uint8_t  DmaSupported : 1;
            common::uint8_t  LbaSupported : 1;
            common::uint8_t  IordyDisable : 1;
            common::uint8_t  IordySupported : 1;
            common::uint8_t  Reserved1 : 1;
            common::uint8_t  StandybyTimerSupport : 1;
            common::uint8_t  Reserved2 : 2;
            common::uint16_t ReservedWord50;
        } Capabilities;
        common::uint16_t ObsoleteWords51[2];
        common::uint16_t TranslationFieldsValid : 3;
        common::uint16_t Reserved3 : 5;
        common::uint16_t FreeFallControlSensitivity : 8;
        common::uint16_t NumberOfCurrentCylinders;
        common::uint16_t NumberOfCurrentHeads;
        common::uint16_t CurrentSectorsPerTrack;
        unsigned long  CurrentSectorCapacity;
        common::uint8_t  CurrentMultiSectorSetting;
        common::uint8_t  MultiSectorSettingValid : 1;
        common::uint8_t  ReservedByte59 : 3;
        common::uint8_t  SanitizeFeatureSupported : 1;
        common::uint8_t  CryptoScrambleExtCommandSupported : 1;
        common::uint8_t  OverwriteExtCommandSupported : 1;
        common::uint8_t  BlockEraseExtCommandSupported : 1;
        unsigned long  UserAddressableSectors;
        common::uint16_t ObsoleteWord62;
        common::uint16_t MultiWordDMASupport : 8;
        common::uint16_t MultiWordDMAActive : 8;
        common::uint16_t AdvancedPIOModes : 8;
        common::uint16_t ReservedByte64 : 8;
        common::uint16_t MinimumMWXferCycleTime;
        common::uint16_t RecommendedMWXferCycleTime;
        common::uint16_t MinimumPIOCycleTime;
        common::uint16_t MinimumPIOCycleTimeIORDY;
        struct {
            common::uint16_t ZonedCapabilities : 2;
            common::uint16_t NonVolatileWriteCache : 1;
            common::uint16_t ExtendedUserAddressableSectorsSupported : 1;
            common::uint16_t DeviceEncryptsAllUserData : 1;
            common::uint16_t ReadZeroAfterTrimSupported : 1;
            common::uint16_t Optional28BitCommandsSupported : 1;
            common::uint16_t IEEE1667 : 1;
            common::uint16_t DownloadMicrocodeDmaSupported : 1;
            common::uint16_t SetMaxSetPasswordUnlockDmaSupported : 1;
            common::uint16_t WriteBufferDmaSupported : 1;
            common::uint16_t ReadBufferDmaSupported : 1;
            common::uint16_t DeviceConfigIdentifySetDmaSupported : 1;
            common::uint16_t LPSAERCSupported : 1;
            common::uint16_t DeterministicReadAfterTrimSupported : 1;
            common::uint16_t CFastSpecSupported : 1;
        } AdditionalSupported;
        common::uint16_t ReservedWords70[5];
        common::uint16_t QueueDepth : 5;
        common::uint16_t ReservedWord75 : 11;
        struct {
            common::uint16_t Reserved0 : 1;
            common::uint16_t SataGen1 : 1;
            common::uint16_t SataGen2 : 1;
            common::uint16_t SataGen3 : 1;
            common::uint16_t Reserved1 : 4;
            common::uint16_t NCQ : 1;
            common::uint16_t HIPM : 1;
            common::uint16_t PhyEvents : 1;
            common::uint16_t NcqUnload : 1;
            common::uint16_t NcqPriority : 1;
            common::uint16_t HostAutoPS : 1;
            common::uint16_t DeviceAutoPS : 1;
            common::uint16_t ReadLogDMA : 1;
            common::uint16_t Reserved2 : 1;
            common::uint16_t CurrentSpeed : 3;
            common::uint16_t NcqStreaming : 1;
            common::uint16_t NcqQueueMgmt : 1;
            common::uint16_t NcqReceiveSend : 1;
            common::uint16_t DEVSLPtoReducedPwrState : 1;
            common::uint16_t Reserved3 : 8;
        } SerialAtaCapabilities;
        struct {
            common::uint16_t Reserved0 : 1;
            common::uint16_t NonZeroOffsets : 1;
            common::uint16_t DmaSetupAutoActivate : 1;
            common::uint16_t DIPM : 1;
            common::uint16_t InOrderData : 1;
            common::uint16_t HardwareFeatureControl : 1;
            common::uint16_t SoftwareSettingsPreservation : 1;
            common::uint16_t NCQAutosense : 1;
            common::uint16_t DEVSLP : 1;
            common::uint16_t HybridInformation : 1;
            common::uint16_t Reserved1 : 6;
        } SerialAtaFeaturesSupported;
        struct {
            common::uint16_t Reserved0 : 1;
            common::uint16_t NonZeroOffsets : 1;
            common::uint16_t DmaSetupAutoActivate : 1;
            common::uint16_t DIPM : 1;
            common::uint16_t InOrderData : 1;
            common::uint16_t HardwareFeatureControl : 1;
            common::uint16_t SoftwareSettingsPreservation : 1;
            common::uint16_t DeviceAutoPS : 1;
            common::uint16_t DEVSLP : 1;
            common::uint16_t HybridInformation : 1;
            common::uint16_t Reserved1 : 6;
        } SerialAtaFeaturesEnabled;
        common::uint16_t MajorRevision;
        common::uint16_t MinorRevision;
        struct {
            common::uint16_t SmartCommands : 1;
            common::uint16_t SecurityMode : 1;
            common::uint16_t RemovableMediaFeature : 1;
            common::uint16_t PowerManagement : 1;
            common::uint16_t Reserved1 : 1;
            common::uint16_t WriteCache : 1;
            common::uint16_t LookAhead : 1;
            common::uint16_t ReleaseInterrupt : 1;
            common::uint16_t ServiceInterrupt : 1;
            common::uint16_t DeviceReset : 1;
            common::uint16_t HostProtectedArea : 1;
            common::uint16_t Obsolete1 : 1;
            common::uint16_t WriteBuffer : 1;
            common::uint16_t ReadBuffer : 1;
            common::uint16_t Nop : 1;
            common::uint16_t Obsolete2 : 1;
            common::uint16_t DownloadMicrocode : 1;
            common::uint16_t DmaQueued : 1;
            common::uint16_t Cfa : 1;
            common::uint16_t AdvancedPm : 1;
            common::uint16_t Msn : 1;
            common::uint16_t PowerUpInStandby : 1;
            common::uint16_t ManualPowerUp : 1;
            common::uint16_t Reserved2 : 1;
            common::uint16_t SetMax : 1;
            common::uint16_t Acoustics : 1;
            common::uint16_t BigLba : 1;
            common::uint16_t DeviceConfigOverlay : 1;
            common::uint16_t FlushCache : 1;
            common::uint16_t FlushCacheExt : 1;
            common::uint16_t WordValid83 : 2;
            common::uint16_t SmartErrorLog : 1;
            common::uint16_t SmartSelfTest : 1;
            common::uint16_t MediaSerialNumber : 1;
            common::uint16_t MediaCardPassThrough : 1;
            common::uint16_t StreamingFeature : 1;
            common::uint16_t GpLogging : 1;
            common::uint16_t WriteFua : 1;
            common::uint16_t WriteQueuedFua : 1;
            common::uint16_t WWN64Bit : 1;
            common::uint16_t URGReadStream : 1;
            common::uint16_t URGWriteStream : 1;
            common::uint16_t ReservedForTechReport : 2;
            common::uint16_t IdleWithUnloadFeature : 1;
            common::uint16_t WordValid : 2;
        } CommandSetSupport;
        struct {
            common::uint16_t SmartCommands : 1;
            common::uint16_t SecurityMode : 1;
            common::uint16_t RemovableMediaFeature : 1;
            common::uint16_t PowerManagement : 1;
            common::uint16_t Reserved1 : 1;
            common::uint16_t WriteCache : 1;
            common::uint16_t LookAhead : 1;
            common::uint16_t ReleaseInterrupt : 1;
            common::uint16_t ServiceInterrupt : 1;
            common::uint16_t DeviceReset : 1;
            common::uint16_t HostProtectedArea : 1;
            common::uint16_t Obsolete1 : 1;
            common::uint16_t WriteBuffer : 1;
            common::uint16_t ReadBuffer : 1;
            common::uint16_t Nop : 1;
            common::uint16_t Obsolete2 : 1;
            common::uint16_t DownloadMicrocode : 1;
            common::uint16_t DmaQueued : 1;
            common::uint16_t Cfa : 1;
            common::uint16_t AdvancedPm : 1;
            common::uint16_t Msn : 1;
            common::uint16_t PowerUpInStandby : 1;
            common::uint16_t ManualPowerUp : 1;
            common::uint16_t Reserved2 : 1;
            common::uint16_t SetMax : 1;
            common::uint16_t Acoustics : 1;
            common::uint16_t BigLba : 1;
            common::uint16_t DeviceConfigOverlay : 1;
            common::uint16_t FlushCache : 1;
            common::uint16_t FlushCacheExt : 1;
            common::uint16_t Resrved3 : 1;
            common::uint16_t Words119_120Valid : 1;
            common::uint16_t SmartErrorLog : 1;
            common::uint16_t SmartSelfTest : 1;
            common::uint16_t MediaSerialNumber : 1;
            common::uint16_t MediaCardPassThrough : 1;
            common::uint16_t StreamingFeature : 1;
            common::uint16_t GpLogging : 1;
            common::uint16_t WriteFua : 1;
            common::uint16_t WriteQueuedFua : 1;
            common::uint16_t WWN64Bit : 1;
            common::uint16_t URGReadStream : 1;
            common::uint16_t URGWriteStream : 1;
            common::uint16_t ReservedForTechReport : 2;
            common::uint16_t IdleWithUnloadFeature : 1;
            common::uint16_t Reserved4 : 2;
        } CommandSetActive;
        common::uint16_t UltraDMASupport : 8;
        common::uint16_t UltraDMAActive : 8;
        struct {
            common::uint16_t TimeRequired : 15;
            common::uint16_t ExtendedTimeReported : 1;
        } NormalSecurityEraseUnit;
        struct {
            common::uint16_t TimeRequired : 15;
            common::uint16_t ExtendedTimeReported : 1;
        } EnhancedSecurityEraseUnit;
        common::uint16_t CurrentAPMLevel : 8;
        common::uint16_t ReservedWord91 : 8;
        common::uint16_t MasterPasswordID;
        common::uint16_t HardwareResetResult;
        common::uint16_t CurrentAcousticValue : 8;
        common::uint16_t RecommendedAcousticValue : 8;
        common::uint16_t StreamMinRequestSize;
        common::uint16_t StreamingTransferTimeDMA;
        common::uint16_t StreamingAccessLatencyDMAPIO;
        unsigned long  StreamingPerfGranularity;
        unsigned long  Max48BitLBA[2];
        common::uint16_t StreamingTransferTime;
        common::uint16_t DsmCap;
        struct {
            common::uint16_t LogicalSectorsPerPhysicalSector : 4;
            common::uint16_t Reserved0 : 8;
            common::uint16_t LogicalSectorLongerThan256Words : 1;
            common::uint16_t MultipleLogicalSectorsPerPhysicalSector : 1;
            common::uint16_t Reserved1 : 2;
        } PhysicalLogicalSectorSize;
        common::uint16_t InterSeekDelay;
        common::uint16_t WorldWideName[4];
        common::uint16_t ReservedForWorldWideName128[4];
        common::uint16_t ReservedForTlcTechnicalReport;
        common::uint16_t WordsPerLogicalSector[2];
        struct {
            common::uint16_t ReservedForDrqTechnicalReport : 1;
            common::uint16_t WriteReadVerify : 1;
            common::uint16_t WriteUncorrectableExt : 1;
            common::uint16_t ReadWriteLogDmaExt : 1;
            common::uint16_t DownloadMicrocodeMode3 : 1;
            common::uint16_t FreefallControl : 1;
            common::uint16_t SenseDataReporting : 1;
            common::uint16_t ExtendedPowerConditions : 1;
            common::uint16_t Reserved0 : 6;
            common::uint16_t WordValid : 2;
        } CommandSetSupportExt;
        struct {
            common::uint16_t ReservedForDrqTechnicalReport : 1;
            common::uint16_t WriteReadVerify : 1;
            common::uint16_t WriteUncorrectableExt : 1;
            common::uint16_t ReadWriteLogDmaExt : 1;
            common::uint16_t DownloadMicrocodeMode3 : 1;
            common::uint16_t FreefallControl : 1;
            common::uint16_t SenseDataReporting : 1;
            common::uint16_t ExtendedPowerConditions : 1;
            common::uint16_t Reserved0 : 6;
            common::uint16_t Reserved1 : 2;
        } CommandSetActiveExt;
        common::uint16_t ReservedForExpandedSupportandActive[6];
        common::uint16_t MsnSupport : 2;
        common::uint16_t ReservedWord127 : 14;
        struct {
            common::uint16_t SecuritySupported : 1;
            common::uint16_t SecurityEnabled : 1;
            common::uint16_t SecurityLocked : 1;
            common::uint16_t SecurityFrozen : 1;
            common::uint16_t SecurityCountExpired : 1;
            common::uint16_t EnhancedSecurityEraseSupported : 1;
            common::uint16_t Reserved0 : 2;
            common::uint16_t SecurityLevel : 1;
            common::uint16_t Reserved1 : 7;
        } SecurityStatus;
        common::uint16_t ReservedWord129[31];
        struct {
            common::uint16_t MaximumCurrentInMA : 12;
            common::uint16_t CfaPowerMode1Disabled : 1;
            common::uint16_t CfaPowerMode1Required : 1;
            common::uint16_t Reserved0 : 1;
            common::uint16_t Word160Supported : 1;
        } CfaPowerMode1;
        common::uint16_t ReservedForCfaWord161[7];
        common::uint16_t NominalFormFactor : 4;
        common::uint16_t ReservedWord168 : 12;
        struct {
            common::uint16_t SupportsTrim : 1;
            common::uint16_t Reserved0 : 15;
        } DataSetManagementFeature;
        common::uint16_t AdditionalProductID[4];
        common::uint16_t ReservedForCfaWord174[2];
        common::uint16_t CurrentMediaSerialNumber[30];
        struct {
            common::uint16_t Supported : 1;
            common::uint16_t Reserved0 : 1;
            common::uint16_t WriteSameSuported : 1;
            common::uint16_t ErrorRecoveryControlSupported : 1;
            common::uint16_t FeatureControlSuported : 1;
            common::uint16_t DataTablesSuported : 1;
            common::uint16_t Reserved1 : 6;
            common::uint16_t VendorSpecific : 4;
        } SCTCommandTransport;
        common::uint16_t ReservedWord207[2];
        struct {
            common::uint16_t AlignmentOfLogicalWithinPhysical : 14;
            common::uint16_t Word209Supported : 1;
            common::uint16_t Reserved0 : 1;
        } BlockAlignment;
        common::uint16_t WriteReadVerifySectorCountMode3Only[2];
        common::uint16_t WriteReadVerifySectorCountMode2Only[2];
        struct {
            common::uint16_t NVCachePowerModeEnabled : 1;
            common::uint16_t Reserved0 : 3;
            common::uint16_t NVCacheFeatureSetEnabled : 1;
            common::uint16_t Reserved1 : 3;
            common::uint16_t NVCachePowerModeVersion : 4;
            common::uint16_t NVCacheFeatureSetVersion : 4;
        } NVCacheCapabilities;
        common::uint16_t NVCacheSizeLSW;
        common::uint16_t NVCacheSizeMSW;
        common::uint16_t NominalMediaRotationRate;
        common::uint16_t ReservedWord218;
        struct {
            common::uint8_t NVCacheEstimatedTimeToSpinUpInSeconds;
            common::uint8_t Reserved;
        } NVCacheOptions;
        common::uint16_t WriteReadVerifySectorCountMode : 8;
        common::uint16_t ReservedWord220 : 8;
        common::uint16_t ReservedWord221;
        struct {
            common::uint16_t MajorVersion : 12;
            common::uint16_t TransportType : 4;
        } TransportMajorVersion;
        common::uint16_t TransportMinorVersion;
        common::uint16_t ReservedWord224[6];
        unsigned long  ExtendedNumberOfUserAddressableSectors[2];
        common::uint16_t MinBlocksPerDownloadMicrocodeMode03;
        common::uint16_t MaxBlocksPerDownloadMicrocodeMode03;
        common::uint16_t ReservedWord236[19];
        common::uint16_t Signature : 8;
        common::uint16_t CheckSum : 8;
        } IDENTIFY_DEVICE_DATA, *PIDENTIFY_DEVICE_DATA;
    }
}

#endif